from enum import Enum

class ProcedureCode(Enum):
    ID_DOWNLINK_NAS_TRANSPORT = 4
    ID_ERROR_INDICATION = 9
    ID_INITIAL_CONTEXT_SETUP = 14
    ID_INITIAL_UE_MESSAGE = 15
    ID_LOCATION_REPORTING_CONTROL = 16
    ID_NGSetup = 21
    ID_PAGING = 24
    ID_PDU_SESSION_RESOURCE_SETUP = 29
    ID_UE_CONTEXT_RELEASE = 41
    ID_UE_CONTEXT_RELEASE_REQUEST = 42
    ID_UPLINK_NAS_TRANSPORT = 46
    ID_HO_REQUIRED = 49
    ID_HANDOVER_COMMAND = 50
    def __str__(self):
        return f"{self.name} ({self.value})"


class MessageType(Enum):
    AUTHENTICATION_REQUEST = 0x56
    SECURITY_MODE_COMMAND = 0x5d
    REGISTRATION_ACCEPT = 0x42
    REGISTRATION_COMPLETE = 0x43
    CONFIGURATION_UPDATE_COMMNAD = 0x54
    UL_NAS_TRANSPORT = 0x67
    DL_NAS_TRANSPORT = 0x68
    PDU_SESSION_ESTABLISHMENT_REQUEST = 0xc1
    SERVICE_REQUEST = 0x4c
    SERVICE_ACCEPT = 0x4e

RAN_UE_NGAP_LEN_LABLES = {
    '00': 1,
    '04': 2,
    '08': 3,
    '0c': 4
}
