
from CryptoMobile.conv import conv_501_A4, conv_501_A2, conv_501_A6
from CryptoMobile.Milenage import Milenage
from pycrate_mobile.TS24008_IE import encode_bcd, decode_bcd

def int_to_bin_str(n, width):
    return bin(n)[2:].zfill(width)

def int_to_hex8(n: int, upper=False) -> str:
    fmt = '{:08X}' if upper else '{:08x}'
    return fmt.format(n & 0xFFFFFFFF)

def int_to_hex4(n: int, upper=False) -> str:
    fmt = '{:04X}' if upper else '{:04x}'
    return fmt.format(n & 0xFFFFFFFF)

def int_to_hex8(n: int, upper=True) -> str:
    fmt = '{:08X}' if upper else '{:08x}'
    return fmt.format(n & 0xFFFFFFFF)

def bcd(chars):  
    bcd_string = ""
    for i in range(len(chars) // 2):
        bcd_string += chars[1+2*i] + chars[2*i]
    bcd_bytes = bytes(bytearray.fromhex(bcd_string))
    return bcd_bytes

def byte_xor(ba1, ba2):
    """ XOR two byte strings """
    return bytes([_a ^ _b for _a, _b in zip(ba1, ba2)])

def calculateRes(opc, k, rand: bytes, sqn_xor_ak: bytes, mnc="099", mcc="460", amf=b"8000"):

    """
    Calculate KSEAF and RES based on the provided parameters using the Milenage algorithm.

    Milenage is a cryptographic algorithm defined by 3GPP TS 35.205 and TS 35.206. It is used in mobile networks 
    (such as 3G, 4G, and 5G) for authentication and key generation. Milenage is based on AES encryption and 
    provides the following functionalities:
    
    - Generation of authentication response (RES) to verify the identity of the user equipment (UE).
    - Generation of confidentiality key (CK) and integrity key (IK) for protecting user data.
    - Generation of anonymity key (AK) to protect user privacy.
    - Calculation of message authentication codes (MAC-A and MAC-S) to ensure message integrity.

    The algorithm takes the following inputs:
    - K: User's secret key (128 bits).
    - OPC: Operator code, used to enhance security.
    - RAND: Random value (128 bits) generated by the network.
    - SQN: Sequence number, used to prevent replay attacks.
    - AMF: Authentication Management Field, used to define the authentication context.

    Outputs of the algorithm include:
    - RES: Authentication response.
    - CK: Confidentiality key.
    - IK: Integrity key.
    - AK: Anonymity key.

    This function uses Milenage to calculate KSEAF and RES based on the provided parameters.

    :param opc: Operator code
    :param k: Key
    :param rand: Random value
    :param sqn_xor_ak: Sequence number XOR with AK
    :param mnc: Mobile Network Code
    :param mcc: Mobile Country Code
    :param amf: AMF value
    :return: Tuple containing KSEAF and RES in hexadecimal format
   """
    SNN = f"5G:mnc{mnc.zfill(3)}.mcc{mcc.zfill(3)}.3gppnetwork.org".encode()
    
    Mil = Milenage(opc)
    Mil.set_opc(opc)
    RES, CK, IK, AK = Mil.f2345(k, rand)
    SQN = byte_xor(AK, sqn_xor_ak)
    mac_a = Mil.f1(k, rand, SQN=SQN, AMF=amf)
    Res = conv_501_A4(CK, IK, SNN, rand, RES)
    KAUSF = conv_501_A2(CK, IK, SNN, sqn_xor_ak)
    KSEAF = conv_501_A6(KAUSF,SNN)
    return KSEAF, Res.hex()

def plmn_bcd_encode(mccmnc):
    mccmnc = str(mccmnc)
    # print("Returning PLMN from: " + str(mccmnc))
    if len(mccmnc)==5:
        return bcd(mccmnc[0] + mccmnc[1] + mccmnc[2] + 'f' + mccmnc[3] + mccmnc[4]) 
    elif len(mccmnc)==6:
        return bcd(mccmnc[0] + mccmnc[1] + mccmnc[2] + mccmnc[3] + mccmnc[4] + mccmnc[5])

    else:
        return b''

def plmn_bcd_decode(bcd_bytes):
    """
    Decode PLMN from BCD encoded bytes.
    
    :param bcd_bytes: BCD encoded bytes representing MCC and MNC
    :return: Decoded PLMN string in the format "MCCMNC"
    """
    plmn = ""
    for byte in bcd_bytes:
       high = (byte >> 4) & 0xF
       low = byte & 0xF
       plmn += str(low) 
       if high != 0xF:
           plmn += str(high)
    return plmn